
---
- name: create  c folder
  hosts: all
  tasks:
    - name: Query pagefiles configuration
      community.windows.win_pagefile:

   - name: Query C pagefile
     community.windows.win_pagefile:
       drive: C

   - name: Set C pagefile, don't override if exists
     community.windows.win_pagefile:
       drive: C
   - initial_size: 1024
     maximum_size: 1024
     override: no
     state: present

   - name: Set C pagefile, override if exists
     community.windows.win_pagefile:
       drive: C
     initial_size: 1024
     maximum_size: 1024
     state: present

   - name: Remove C pagefile
     community.windows.win_pagefile:
       drive: C
     state: absent

   - name: Remove all current pagefiles, enable AutomaticManagedPagefile and query at the end
     community.windows.win_pagefile:
       remove_all: yes
     automatic: yes

   - name: Remove all pagefiles disable AutomaticManagedPagefile and set C pagefile
     community.windows.win_pagefile:
       drive: C
     initial_size: 2048
     maximum_size: 2048
     remove_all: yes
     automatic: no
     state: present

   - name: Set D pagefile, override if exists
     community.windows.win_pagefile:
       drive: d
     initial_size: 1024
     maximum_size: 1024
     state: present
